### ISSUE TITLE
does not export CloudModule

### ISSUE THREAD

**Issue by numerized** [driftyco/ionic-cloud-angular#21] opened 2016-09-30 18:02 UTC
Hi Team

Amazing work. Astonishing even...:))

Look what I have when I follow the docs with Ionic.io
If you need more infos ping me

ionic info
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.2.0
Xcode version: Xcode 7.3.1 Build version 7D1014

```
[18:57:43]  lint finished in 2.38 s
[18:57:46]  typescript compiler ready in 5.77 s
[18:57:46]  bundle dev started ...
[18:57:53]  Error: Module /Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/@ionic/cloud-angular/dist/es5/index.js does not export CloudModule (imported by /Users/numerized/Work/00_Github/00_Emoviser_rc0_2/.tmp/app/app.module.js)
    at Module.trace (/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/rollup/dist/rollup.js:7677:29)
    at ModuleScope.findDeclaration (/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/rollup/dist/rollup.js:7300:22)
    at Scope.findDeclaration (/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/rollup/dist/rollup.js:5351:39)
    at MemberExpression.bind (/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/rollup/dist/rollup.js:6666:28)
    at /Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/rollup/dist/rollup.js:5151:50
    at CallExpression.eachChild (/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/rollup/dist/rollup.js:5168:5)
    at CallExpression.bind (/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/rollup/dist/rollup.js:5151:7)
    at CallExpression.bind (/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/rollup/dist/rollup.js:5842:23)
    at /Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/rollup/dist/rollup.js:5151:50
    at ArrayExpression.eachChild (/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/rollup/dist/rollup.js:5165:19)

[18:57:53]  sass started ...
[18:57:53]  build dev failed:  Build failed: ENOENT: no such file or directory, scandir '/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/.tmp/node_modules/ionic-angular/components/action-sheet'

[18:57:53]  Error: ENOENT: no such file or directory, scandir '/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/.tmp/node_modules/ionic-angular/components/action-sheet'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at getSiblingSassFiles (/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/@ionic/app-scripts/dist/sass.js:126:17)
    at addComponentSassFiles (/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/@ionic/app-scripts/dist/sass.js:100:24)
    at /Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/@ionic/app-scripts/dist/sass.js:95:9
    at Array.forEach (native)
    at getComponentSassFiles (/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/@ionic/app-scripts/dist/sass.js:94:26)
    at generateSassData (/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/@ionic/app-scripts/dist/sass.js:79:30)
    at Object.sass (/Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/@ionic/app-scripts/dist/sass.js:38:9)
    at /Users/numerized/Work/00_Github/00_Emoviser_rc0_2/node_modules/@ionic/app-scripts/dist/build.js:63:23
```

**Comment by numerized** [comment] 2016-09-30 18:08
Going to try to export members through Rollup systemJS injector.

**Comment by numerized** [comment] 2016-09-30 18:11
then I have : 

```
SyntaxError: Duplicate export 'CloudModule'
```

**Comment by numerized** [comment] 2016-09-30 20:10
To make it work with rc0 I had to add this to my file rollup.config.js

node_modules/@ionic/app-scripts/config/rollup.config.js

```
module.exports = {

  [...]
  useStrict: false,
   [...]

  plugins: [
    ngTemplate(),
    commonjs({
        include: [
         [...]
        'node_modules/@ionic/cloud-angular/**',
        'node_modules/superagent/**',
        'node_modules/@ionic/cloud/node_modules/superagent/**',
        'node_modeule/emitter/**',
        'node_modules/reduce-component/**',
        'node_modules/intl/**',
        'node_modules/**',
        ],
        namedExports: {
          [...]
        }
    }),
    nodeResolve({
      useStrict: false,
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    })
  ]

};
```

**Comment by ericb** [comment] 2016-10-04 19:25
What version of the cloud client are you using?

**Comment by mlynch** [comment] 2016-10-04 21:59
Hey @numerized, I just tested this with 0.5.2 of `@ionic/cloud-angular` and it's working fine. Make sure you npm install to get the latest version and if it's still an issue let us know. Closing as can't reproduce for now.

**Closed as completed by mlynch** 2016-10-04 21:59 UTC

**Comment by barbsicle** [comment] 2016-10-05 05:44
Hi,

I am also having a similar error on 0.5.2, which is giving me the error below. Using the fix by @numerized works but makes the build process extremely slow.

```
[12:35:07]  bundle dev failed:  Module C:\Users\User\Desktop\project\node_modules\@ionic\cloud-angular\dist\es5\index.js does not export CloudModule (imported by C:\Users\User\Desktop\project\.tmp\app\app.module.js)
[12:35:07]  bundle dev failed:  Module C:\Users\User\Desktop\project\node_modules\@ionic\cloud-angular\dist\es5\index.js does not export CloudModule (imported by C:\Users\User\Desktop\project\.tmp\app\app.module.js)

[12:35:07]  Error: Module C:\Users\User\Desktop\project\node_modules\@ionic\cloud-angular\dist\es5\index.js does not export CloudModule (imported by C:\Users\User\Desktop\project\.tmp\app\app.module.js)
    at Module.trace (C:\Users\User\Desktop\project\node_modules\rollup\dist\rollup.js:7706:29)
    at ModuleScope.findDeclaration (C:\Users\User\Desktop\project\node_modules\rollup\dist\rollup.js:7329:22)
    at Scope.findDeclaration (C:\Users\User\Desktop\project\node_modules\rollup\dist\rollup.js:5349:39)
    at MemberExpression.bind (C:\Users\User\Desktop\project\node_modules\rollup\dist\rollup.js:6695:28)
    at C:\Users\Shing\Desktop\project\node_modules\rollup\dist\rollup.js:5149:50
    at CallExpression.eachChild (C:\Users\User\Desktop\project\node_modules\rollup\dist\rollup.js:5166:5)
    at CallExpression.bind (C:\Users\User\Desktop\project\node_modules\rollup\dist\rollup.js:5149:7)
    at CallExpression.bind (C:\Users\User\Desktop\project\node_modules\rollup\dist\rollup.js:5850:23)
    at C:\Users\Shing\Desktop\project\node_modules\rollup\dist\rollup.js:5149:50
    at ArrayExpression.eachChild (C:\Users\User\Desktop\project\node_modules\rollup\dist\rollup.js:5163:19)   
```

`ionic info` output:

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0
```

**Comment by barbsicle** [comment] 2016-10-06 03:31
Doing some testing. If it's a starter project, bootstrapping `CloudModule` seems to work just fine. Not sure what's going wrong here...will continue to feedback on any further findings.

**Comment by ericb** [comment] 2016-10-06 03:37
@barbsicle Are you certain you're using the latest Ionic 2 RC0 with that 0.5.2 release of cloud-angular?

**Comment by barbsicle** [comment] 2016-10-07 12:48
Hi everyone,

I have resolved all issues with the above. The remedy was to start a new project from scratch, and run `npm install @ionic/cloud-angular --save` as well as other installs for third-party libraries before importing the existing codebase. Mysterious, but it worked.

Thanks @ericb for checking on me!

**Comment by numerized** [comment] 2016-10-11 23:29
Thanks for replies I'll give it a go soon.

**Comment by candidosales** [comment] 2016-10-13 17:46
I deleted the node_modules folder and reinstall everything again, is now working.

**Comment by numerized** [comment] 2016-10-15 18:33
Hi guys, 

Still problem exists after migrating to RC1 and deleting my node_modules folders.

Here's my package.json

```
{
  "name": "emoviser",
  "author": "Kévin Perrée",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "dependencies": {
    "@angular/common": "^2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "^2.0.0",
    "@angular/forms": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.0",
    "@angular/platform-browser-dynamic": "^2.0.0",
    "@angular/platform-server": "^2.0.0",
    "@ionic/cloud-angular": "^0.5.2",
    "@ionic/storage": "^1.0.3",
    "@types/core-js": "^0.9.34",
    "@types/request": "0.0.31",
    "angularfire2": "^2.0.0-beta.5",
    "chart.js": "^2.3.0",
    "cordova-non-renewing-subscription": "^1.0.1",
    "debug": "^2.2.0",
    "firebase": "^3.4.1",
    "intl": "^1.2.5",
    "ionic-angular": "^2.0.0-rc.1",
    "ionic-native": "^2.2.3",
    "ionicons": "^3.0.0",
    "ng2-charts": "^1.3.0",
    "require": "^2.4.20",
    "rollup-plugin-commonjs": "^5.0.4",
    "rollup-plugin-node-resolve": "^2.0.0",
    "rollup-plugin-replace": "^1.1.1",
    "rollup-plugin-uglify": "^1.0.1",
    "rxjs": "^5.0.0-beta.12",
    "superagent": "^2.3.0",
    "whatwg-fetch": "^1.0.0",
    "whatwg-streams": "^0.1.1",
    "zone.js": "^0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.34",
    "@types/request": "0.0.30",
    "ng2-chartjs2": "^1.2.0",
    "rollup-plugin-node-builtins": "^1.2.1",
    "rollup-plugin-node-globals": "^1.0.9",
    "rollup-plugin-node-resolve": "^2.0.0",
    "typescript": "^2.0.3"
  },
  "description": "00_Emoviser_rc0_2: An Ionic project"
}
```

and my rollup.config.js

```
var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var globals = require('rollup-plugin-node-globals');
var builtins = require('rollup-plugin-node-builtins');
var json = require('rollup-plugin-json');


// https://github.com/rollup/rollup/wiki/JavaScript-API

var rollupConfig = {
  /**
   * entry: The bundle's starting point. This file will
   * be included, along with the minimum necessary code
   * from its dependencies
   */
  entry: '{{SRC}}/app/main.dev.ts',

  /**
   * sourceMap: If true, a separate sourcemap file will
   * be created.
   */
  sourceMap: true,

  /**
   * format: The format of the generated bundle
   */
  format: 'iife',

  /**
   * dest: the output filename for the bundle in the buildDir
   */
  dest: 'main.js',
  useStrict: false,

  /**
   * plugins: Array of plugin objects, or a single plugin object.
   * See https://github.com/rollup/rollup/wiki/Plugins for more info.
   */
  plugins: [
    builtins(),
    commonjs({
        include: [
        'node_modules/rxjs/**',
        'node_modules/firebase/**',
        'node_modules/angularfire2/**'
        ],
        namedExports: {
        'node_modules/firebase/firebase.js': ['initializeApp', 'auth', 'database'],
        'node_modules/angularfire2/node_modules/firebase/firebase-browser.js': ['initializeApp', 'auth', 'database']
        }
    }),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    }),
    globals(),
    json()
  ]

};


if (process.env.IONIC_ENV == 'prod') {
  // production mode
  rollupConfig.entry = '{{TMP}}/app/main.prod.ts';
  rollupConfig.sourceMap = false;
}


module.exports = rollupConfig;

```

**Comment by sp3rk** [comment] 2016-12-22 22:51
anything new? ... have the same error.
