### ISSUE TITLE
Ionic Deploy failing on extract

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic-cloud-angular#12] opened 2016-08-25 05:13 UTC
Hey guys!

Sorry to keep bothering you with this plugin, but since the latest update (angular-cloud: 0.0.19 and ionic-plugin-deploy: 0.6.2), I'm having trouble updating my app.  My scenario is as follows:
- I was previously using the `update()` method to get the latest version after running `check()`
- With the latest version it would seem as though the update() method is gone, so I'm now using check(), download(), extract() to get and install the latest.  
- Right now check() tells me there is an update, download() seems to finish succesfully, but the "extract()" does not.  There isn't an error, but the "success" value is "false".

My current code is below:

```
this.deploy.check().then(updateAvailable => {            
            if (updateAvailable) {
                this.loadingService.show('Updating app to the latest and greatest...').then(() => {
                    this.deploy.download().then(success => {                        
                        this.deploy.extract().then(success => {                            
                            let message = success ? 'Update successfully installed.  Restarting now...' : 'An error occurred while extracting the app';  // success is false
                            this.handleUpdateResponse(message, true, !!success);
                        }).catch(err => {                            
                            this.handleUpdateResponse('An error occurred while extracting the update.', true);
                        });                        
                    }).catch(err => {                        
                        this.handleUpdateResponse('An error occurred while updating the app: ' + err, true);
                    });
                });
            }
            else {
                this.handleUpdateResponse(null);
            }
        }).catch(err => {            
            console.error('An error occurred while checking for latest version', err);
            this.handleUpdateResponse(null);
        });
```

**Comment by Fuiste** [comment] 2016-08-25 15:25
@joshgarwood `extract()` will simply extract the update and save it to your device, to actually apply it you will then need to call `load()`.

Here's an example from one of my testing apps:

``` typescript
  deploy.check().then((hasUpdate: boolean) => {
    if (hasUpdate) {
      deploy.download().then(() => {
        deploy.extract().then(() => {
          deploy.load();
        }, (error) => {
          console.log("Error extracting: " + error);
        })
      }, (err) => {
        console.log("Error downloading: " + err);
      });
    }
  }, (cErr) => {
    console.log("Check error: " + cErr);
  })
```

As to your extract failing, I'd look to your logs to see if any errors are happening.  I can't be certain what's going on from the code above, and can't reproduce the issue.

**Comment by imhoffd** [comment] 2016-08-25 15:51
@joshgarwood We don't recommend calling `load()`, though, as it immediately refreshes the app, instead of just loading up the new app snapshot when the app is started again. Are you on Android or iOS?

**Comment by joshgarwood** [comment] 2016-08-25 16:06
Hey guys!  Thanks so much for the quick responses.  

@Fuiste I am actually calling `deploy.load()` in my `handleUpdateResponse()` function if the extract was successful.  But it never gets called because the `success` parameter in the `extract()` callback is always false.  As well, my logs don't indicate any failure.  In looking at the ionic-cloud deploy.ts (line 169), there isn't any log output for this scenario... The `extract()` doesn't throw an error, it's just that `success` is false.  

@dwieeb  That's definitely good to know.  I am currently calling `load()` in the event of a successful extract... are there potential issues with that?  I've seen some odd behavior (such as my app _always_ going back to the splash screen after opening from the background).  I am on Android.

Thanks again guys, y'all are awesome!

**Comment by joshgarwood** [comment] 2016-08-29 16:28
Sorry to be such a pest, but do either of you know if it's possible to expose a more useful error message (or add more detailed logging) for the `extract()` method in the deploy plugin?  That may help me diagnose my issue.

Thanks!

**Comment by imhoffd** [comment] 2016-08-29 16:41
@joshgarwood The error messages from the deploy plugin are going to be very unhelpful. We're aware of this and we want to take a look at modernizing the plugin and perhaps providing a better API as soon as we can. For now, you can do `adb logcat` and try to look at the deploy plugin logs. You should be able to grep for "IONIC".

**Comment by ibcooley** [comment] 2016-09-02 21:25
Similar to @joshgarwood, i've seen an issue where the extract method promises to return a boolean, but returns false even if successful.  Perhaps that is the problem?

From your examples above, it appears  that you disregard the boolean return value as it comes from extract.  Is that intentional?

My code is below

```
this.deploy.download().then((success) => {
    let message = success ? 'Update successfully installed.' : 'An error occurred while updating the app';
    if (success) {
        this.deploy.extract().then(success => {
                        //TODO: proper extraction success checking
            console.log("extract success: " + success); //is false
            this.deploy.load();
        }).catch(err => console.log("Extract Failed:" + JSON.stringify(err)));
    }
    this.loading.hide().then(() => { resolve(message) });
}).catch(err => {
    this.loading.hide().then(() => { resolve('An error occurred while updating the app: ' + err) });
});
```

**Comment by imhoffd** [comment] 2016-09-02 21:28
What devices are you guys trying this on (specifically)? @joshgarwood @ibcooley

**Comment by ibcooley** [comment] 2016-09-02 21:34
@joshgarwood and I work on the same dev team, btw.
But our team has had issues with the following:
- iPhone 6
- Genymotion Emulator
- HTC M8

My ADB log when extracting is completing looks like this:

```
09-02 17:09:30.517 29524 29598 I IONIC.DEPLOY.EXTRACT: Progress: 90%
09-02 17:09:30.518 29524 29598 I IONIC.DEPLOY.EXTRACT: Progress: 92%
09-02 17:09:30.519 29524 29598 I IONIC.DEPLOY.EXTRACT: Progress: 93%
09-02 17:09:30.524 29524 29524 W art     : Attempt to remove non-JNI local reference, dumping thread                    09-02 17:09:30.538 29524 29598 I IONIC.DEPLOY.EXTRACT: Progress: 95%
09-02 17:09:30.540 29524 29598 I IONIC.DEPLOY.EXTRACT: Progress: 96%
09-02 17:09:30.543 29524 29598 I IONIC.DEPLOY.EXTRACT: Progress: 98%
09-02 17:09:30.543 29524 29598 I IONIC.DEPLOY.EXTRACT: Progress: 100%
09-02 17:09:30.554 29524 29598 I IONIC.DEPLOY.REMOVE: Removed www.zip
09-02 17:09:30.590 29524 29524 W art     : Attempt to remove non-JNI local reference, dumping thread
09-02 17:09:30.657 29524 29524 W art     : Attempt to remove non-JNI local reference, dumping thread
09-02 17:09:30.700 29524 29524 I chromium: [INFO:CONSOLE(29)] "extract success: false", source: http://192.168.1.2:8100/ (29)
09-02 17:09:30.700 29524 29524 I IONIC.DEPLOY.REDIRECT: Loading deploy version: a0550e7a-7137-11e6-8871-bed395d43cc5
```

Notice the "extract success: false" line.

**Comment by Fuiste** [comment] 2016-09-02 21:48
@ibcooley and @joshgarwood whoops, looks like we weren't resolving the `extract` promise correctly, we're working on a fix right now and will update you soon!

Mentioning this here, but it's just as applicable to https://github.com/driftyco/ionic-cloud-angular/issues/13#event-776928891

**Comment by ibcooley** [comment] 2016-09-02 21:55
That is excellent news!
:+1:

**Closed as completed** 2016-09-02 22:19 UTC

**Comment by Fuiste** [comment] 2016-09-02 22:20
@ibcooley and @joshgarwood we just released a new version of `ionic-cloud-angular` which addresses the issue (`0.4.0`).

We've changed the `download` and `extract` promises to simply resolve on success and reject on failure, rather than resolving with a boolean, so your code may change slightly as a result.

Let us know if you still have any issues!

**Comment by ibcooley** [comment] 2016-09-02 22:27
@Fuiste, you guys are quick!  thanks!  We should be able to test this soon and let you know if it doesn't work, as expected.

edit: this seems to address one of the issues we were seeing!  Will keep you updated on additional problems we may run into.
