### ISSUE TITLE
auth.requestPasswordReset(email) not working 

### ISSUE THREAD

**Issue by mo-mueller** [driftyco/ionic-cloud-angular#32] opened 2016-11-13 09:53 UTC
I'm trying to implement the Ionic Cloud Auth Service and now I want to do the password reset like it is described [here](https://docs.ionic.io/services/auth/#using-the-client). So I have a text field where the user can enter his email and a button. 

Here is my pw-reset.html:

```
<ion-header>
  <ion-navbar>
    <ion-title>New Password</ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
    <ion-item>
        <ion-label color="primary" stacked>E-Mail</ion-label>
        <ion-input [(ngModel)]="email"></ion-input>
    </ion-item>
    <br />
    <button ion-button (click)="sendPasswordRequest();">New Password</button>
</ion-content>
```

And here is my pw-reset.ts:

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Auth, User, UserDetails, IDetailedError } from '@ionic/cloud-angular';
import { ConfirmPasswordResetPage } from '../confirm-password-reset/confirm-password-reset';

@Component({
  selector: 'page-pw-reset',
  templateUrl: 'pw-reset.html'
})
export class PwResetPage {
    email: any;

    constructor(public navCtrl: NavController, public auth: Auth) {}

    sendPasswordRequest() {
        this.auth.requestPasswordReset(this.email);
        this.navCtrl.push(ConfirmPasswordResetPage);
    }
}
```

And here are the errors which come when I click on the button:

![error](https://cloud.githubusercontent.com/assets/15029638/20244800/4610fee8-a98f-11e6-9bcd-9f37646d48f2.png)

**Comment by RandyLedbetter** [comment] 2016-11-20 18:39
I am having the same issue when running "@ionic/cloud-angular": "^0.7.0". 
The same this.storage 'undefined' error within Auth.requestPasswordReset(email:string).  Version 0.6.0 produced the same error. Dialing the version back to 0.5.2  in package.json and running npm update allowed the email with the six digit code to be sent with my implementation, which is programatically similar to the original reporter's approach outlined above. Not great, but a temporary fix for those still in development.

**Comment by ericb** [comment] 2016-11-22 15:24
Closing this as a duplicate of driftyco/ionic-cloud#81

**Closed as completed by ericb** 2016-11-22 15:24 UTC
Labels: duplicate
